### ISSUE TITLE
A handful of questions

### ISSUE THREAD

**Issue by assarbad** [unit72784/Diabolic-Drive#1]
Hi there, you write you have a version of WifiDuck preloaded. Has that been changed by you beyond the mere cosmetics (e.g. the logo) or could one go [to their repo](https://github.com/SpacehuhnTech/WiFiDuck) and build based on it and flash that? I'll probably try that first, even if you should happen not to respond へ‿(ツ)‿ㄏ

Just trying to get my hands dirty with the two diabolic drives I received. First goal of mine is to get it going it without having to get the full Arduino IDE.

Also, would you mind enabling discussions for the project here on GitHub? Discussions can be added in the general settings:

![Screenshot_20240830_213819](https://github.com/user-attachments/assets/6b5de6f1-dc6d-4a51-8c5e-01ac1f1e5029)

And on another note it may make more sense to move the project to a GitHub organization of its own if you know you'll need multiple repos (e.g. to host your DD-specific customizations of WifiDuck).

And last but not least: thanks for the project and making it available through CrowdSupply!

Oliver

PS: you didn't ask for advice, but I threw in some ideas since you wrote it's your first repo. Hope you don't mind. I don't mean to impose, though.

**Comment by unit72784** [comment]
@assarbad Hello Oliver!
> Has that been changed by you beyond the mere cosmetics (e.g. the logo) or could one go [to their repo](https://github.com/SpacehuhnTech/WiFiDuck) and build based on it and flash that?

Developing unique software for the Diabolic Drive is still ongoing! I know that many months passed without releasing it yet, but I was super busy until this moment with other things regarding the hardware design, which is my main job! But I'll intensively work on the software side in the coming months and feel completely free to develop yours based on the wifiduck firmware, which is fully supported by the Diabolic Drive, and you can flash it to yours using the custom board files and the instructions provided in this repo, but it will not give you anything beyond the already preloaded firmware in your Diabolic Drive, and you will lose the SPECTRE feature, which makes your Diabolic Drive dormant until you activate it.

>Also, would you mind enabling discussions for the project here on GitHub? Discussions can be added in the general settings:

Done!

>And on another note it may make more sense to move the project to a GitHub organization of its own if you know you'll need multiple repos (e.g. to host your DD-specific customizations of WifiDuck).

I'm sorry, but I think I didn't catch this. Can you please explain more because I didn't understand it? You mean making a GitHub account with the name of the Diabolic Drive, and this account hosts many repos related to the Diabolic Drive?

> And last but not least: thanks for the project and making it available through CrowdSupply!

You are most welcome!

> PS: you didn't ask for advice, but I threw in some ideas since you wrote it's your first repo. Hope you don't mind. I don't mean to impose, though.

Never mind at all, and all you wrote is much appreciated. Feel free to reach out to me whenever you need help. :)

**Comment by assarbad** [comment]
Hello Omar,

> Developing unique software for the Diabolic Drive is still ongoing! I know that many months passed without releasing it yet, but I was super busy until this moment with other things regarding the hardware design, which is my main job! But I'll intensively work on the software side in the coming months and feel completely free to develop yours based on the wifiduck firmware, which is fully supported by the Diabolic Drive, and you can flash it to yours using the custom board files and the instructions provided in this repo, but it will not give you anything beyond the already preloaded firmware in your Diabolic Drive, and you will lose the SPECTRE feature, which makes your Diabolic Drive dormant until you activate it.

Fair enough. I think the SPECTRE feature is probably something I'd be able to figure out as well. But the initial idea by you was certainly something I would not have come up with as easily.

> Done!

Thanks!

> I'm sorry, but I think I didn't catch this. Can you please explain more because I didn't understand it? You mean making a GitHub account with the name of the Diabolic Drive, and this account hosts many repos related to the Diabolic Drive?

Yes, it'd be separate from your user account, you are in full control by default if you create an organization and you can give it a name of your choice. Essentially it could be something like `Diabolic-Drive/firmware` and other repos than `firmware`. You also have additional features there such teams (essentially user groups), discussions (again), a landing page for the org and projects. Just an idea.

> Never mind at all, and all you wrote is much appreciated. Feel free to reach out to me whenever you need help. :)

Cool, thanks 👍
